### ISSUE TITLE
Android compatibility 

### ISSUE THREAD

**Issue by mbnoimi** [AlterX76/VirtualKeyboard#2]
Current version (https://github.com/AlterX76/VirtualKeyboard/commit/f73e7bde263ff7a69e90e25d391d8a8ba5b907cd) isn't compatible with Android so I'm planning to modify widget layout to a similar layout (This is Google's software keyboard).

Before start my modifications, Do you've any suggestions?
- English layout
  ![photo_2016-01-07_11-10-21](https://cloud.githubusercontent.com/assets/284547/12166604/d54a131a-b52f-11e5-94de-8441ecf552c6.jpg)
- Arabic layout
  ![photo_2016-01-07_11-10-09](https://cloud.githubusercontent.com/assets/284547/12166603/d5305c86-b52f-11e5-8641-52fd762ca281.jpg)

**Comment by AlterX76** [comment]
You want to change layout in general as above or only for OS specific?

**Comment by AlterX76** [comment]
You can create in the widgetKeyboard a second optional parameter as enum for all the supported OS (e.g. android or iso and so on...). Inside the class use the bool param to understand which layout to use

**Comment by mbnoimi** [comment]
> You want to change layout in general as above or only for OS specific?

only for OS specific

**Comment by mbnoimi** [comment]
> You can create in the widgetKeyboard a second optional parameter as enum for all the supported OS (e.g. android or iso and so on...). Inside the class use the bool param to understand which layout to use

Actually this is what I'm planning to (you already use embed param, I'll create alternative to it) but I just want to inquiry you what if you've any ideas to share with me before starting up.

**Comment by AlterX76** [comment]
Ok...so I think this is all...you can start your journey :+1:

**Comment by roke-julian-lockhart** [comment]
@mbnoimi, where is your fork, and shall you upstream it to here? For an originally solely-Linux keyboard to gain support for Android would ultimately be decently trivial, but significant nonetheless.
