### ISSUE TITLE
Space does not Work

### ISSUE THREAD

**Issue by SeppR894** [AlterX76/VirtualKeyboard#4]
Hi AlterX76

I have been trying for 2 days but I can´t get any solution.
The problem is that if I press the Space-Bar on teh VirtualKeyboard nothing happens (only the cursor dissapears)
if I repalce the " " to "-" (or any other letter) for the KEY_SPACE it works fine 
only the  -->" "<-- does not work.

very strange: if ia try -->"       ."<--- the spaces are erased and only the dot is shown.

I use Qt 5.9.3

Would be very happy if you could help me.
Thank you.

**Comment by AlterX76** [comment]
Hi I will try this out to better understand this problem as soon as I can.

**Comment by SeppR894** [comment]
That wuold be great Tahnk You!

Im a fan of your keyboard, becaus ecept for the SPACE it works great and it is very easy to use thanks

**Comment by AlterX76** [comment]
Thanks reporting this. It seems a bug. I will have a look at this

**Comment by AlterX76** [comment]
Problem has been fixed and commited.

**Comment by SeppR894** [comment]
Thank you very much
