### ISSUE TITLE
How to access?

### ISSUE THREAD

**Issue by iandoug** [AlterX76/VirtualKeyboard#5]
Hi
I have this installed (on Gentoo), but how do I access it?

Can you please add something to the readme?

thanks, Ian

**Comment by AlterX76** [comment]
Hello,
could you be more specific? This is an open source keyboard: you can download it, compile in your project and use it.

**Comment by iandoug** [comment]
Is this basically a "component" for another application rather than a stand-alone on-screen keyboard?

Comparing to Florence, for example.
http://florence.sourceforge.net/english.html

Thanks, Ian

**Comment by AlterX76** [comment]
Exactly! This is a source code to integrate into an app a developer is creating...

**Comment by roke-julian-lockhart** [comment]
@AlterX76, any chance that it shall become possible to invoke separately?
